### ISSUE TITLE
Invalid format of composer.json file.

### ISSUE THREAD

**Issue by tarata** [padraic/humbug#101]
When I ran `composer install`, I got this error.

```
$composer install



  [UnexpectedValueException]
  Could not parse version constraint ^1.0.2: Invalid version string "^1.0.2"



install [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--no-plugins] [--no-custom-installers] [--no-scripts] [--no-progress] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [--ignore-platform-reqs] [packages1] ... [packagesN]
```

**Comment by padraic** [comment]
The caret operator is a valid version constraint on mini version? The package in question is semantically versioned and I've had no issues installing here.

https://getcomposer.org/doc/01-basic-usage.md#next-significant-release-tilde-and-caret-operators-

**Comment by Anahkiasen** [comment]
Just do `composer self-update`, it's a recent feature of Composer

**Comment by tarata** [comment]
Thanks @padraic and @Anahkiasen .

When I ran `php composer.phar validate` after running `php -r "readfile('https://getcomposer.org/installer');" | php`, the console said `./composer.json is valid`.

My composer's version is `1.0.0-alpha9` and latest composer.phar's version is `1.0-dev (1d8f05f1dd0e390f253f79ea86cd505178360019)`, so this occurred.
My composer is installed by `brew install composer` on Mac.

If the composer is latest, this composer.json is valid, so this issue is needless I think.

Please listen as just a question.
If I run `brew install composer`, the composer's version is `1.0.0-alpha9` now.
Then, what should I do??
I mean should I run `composer self-update` ?
 or should I run `php -r "readfile('https://getcomposer.org/installer');" | php` to install the latest composer.phar ??

**Comment by GrahamCampbell** [comment]
Ypu need a version newer than 1.0.0-alpha9.
