### ISSUE TITLE
make humbug installable via composer require

### ISSUE THREAD

**Issue by samsonasik** [padraic/humbug#103]
currently, humbug can't be installed directly via composer require : 
```
$ composer require humbug/humbug 1.0.*@dev
./composer.json has been created
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for humbug/humbug 1.0.*@dev -> satisfiable by humbug/humbug[1.0.x-dev].
    - humbug/humbug 1.0.x-dev requires padraic/phpunit-extensions ~1.0@dev -> no matching package found.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.

Read <http://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

Installation failed, deleting ./composer.json.
```

**Comment by GrahamCampbell** [comment]
This isn't a bug. You need to set your "minimum-stability" to dev. This is just one reason why composer's require command is bad imo.

**Comment by padraic** [comment]
```sh
composer require humbug/humbug:1.0.*@dev
```
I think you can swing it with the colon separator before the version? I actually did something similar today while cleaning up Mockery's travis scripts and build deps: https://github.com/padraic/mockery/blob/travis-cleanup/travis/install.sh

**Comment by GrahamCampbell** [comment]
@padraic That's a really crap solution though.

**Comment by padraic** [comment]
@GrahamCampbell It's hideous

Will do if anyone really really needs this until stable releases of Humbug and phpunit-extensions (and the phar) are available. Mockery uses it solely for the Travis builds and I'm removing coveralls thereafter from composer.json.

**Comment by samsonasik** [comment]
@padraic try without --dev : 
```
composer require humbug/humbug:1.0.*@dev padraic/phpunit-extensions:~1.0@dev
```
and it works. should readme be updated ?

**Comment by padraic** [comment]
I'd prefer people update their composer.json, do a global install, or have a self-updating phar. Humbug really doesn't even target composer.json - it's an infrequent use development tool. Perhaps I should simply get regular phars rolling?

**Comment by samsonasik** [comment]
+1 for phar it.

**Comment by padraic** [comment]
Phar builds have been implemented via box. I had to write my own self-update based loosely off composer's. The revised self update enforces TLS and checks phar signatures.

Closing since this is the preferred install option, other than a bleeding edge clone which is best for debugging/testing.

**Comment by samsonasik** [comment]
thank you @padraic ;)

**Comment by padraic** [comment]
@samsonasik Currently broken unfortunately. There is an odd ioctl error popping up. I just built a phar, tested (worked!), uploaded and self-updated somwhere. Error. Then I built again, tested, and it was there during testing. Not sure if it's box or something codewise. Will need to do some digging with build options...

Ordinary clone copy works perfectly every time.
