### ISSUE TITLE
Bootstrap location XmlConfiguration::handleSuite

### ISSUE THREAD

**Issue by rollenes** [padraic/humbug#107]
In order to finish #104 i got questions to XmlConfiguration::handleSuite method.
https://github.com/padraic/humbug/blob/master/src/Adapter/Phpunit/XmlConfiguration.php#L221

It is called here: https://github.com/padraic/humbug/blob/master/src/Adapter/Phpunit/XmlConfiguration.php#L163

The logic: Get the first defined testsuite and in its direcories search for bootstrap.php file in those direcories. 
PhpUnit does not work this way. It looks for bootstrap configuration. If it ommits bootstrap location(as in comment in line 174) its just because configuration does not contain bootstrap.

So I found this part of code as dead. Am I right? Or maybe there are some other reasons to maintain this code?

**Comment by padraic** [comment]
@rollenes That area will be very iffy code so feel free to amend as you see fit. It's literally my last feature task for phpunit to implement multi-suite support. However, I also need to update the related phpunit-extensions package for that first so any suite merging is optional, not required). I suspect there is a last ditch "look anywhere" element to what you're seeing, to locate a bootstrap.php but I struggle to recall exactly why it was written in!

**Comment by rollenes** [comment]
Thanks @padraic. My guess why it was written in is that someone has IDE configured to use bootstrap defined as bootstrap.php and everything works fine in IDE, but not outside IDE.
I removed this iffy code.
