### ISSUE TITLE
self-update fails: Current version check has failed. Please try again.

### ISSUE THREAD

**Issue by andrewholgate** [padraic/humbug#108]
Using Ubuntu 14.04, I receive the error `Current version check has failed. Please try again.` when running `./humbug.phar self-update`

How to reproduce:
```
wget https://padraic.github.io/humbug/downloads/humbug.phar
chmod +x humbug.phar
wget https://padraic.github.io/humbug/downloads/humbug.phar.pubkey
./humbug.phar self-update
```

**Comment by padraic** [comment]
@andrewholgate Here's what I get:

```
Humbug is currently up to date.
Current SHA-1 hash is: deb30fe077db4298d6cc387337b37d58b48794ee.
```
Can you re-check? If still a problem, it's possibly an issue establishing a TLS connect. All that occurs behind the scenes is fetching `https://padraic.github.io/humbug/downloads/humbug.version` and comparing that to the current phar SHA-1. What I can do is run a check prior to a self-update to see if that's likely to be an issue and allow errors from the remote fetch to bubble out as more informative exceptions.

Though if you can run Composer's installer, which also enforces TLS (or should), you should be fine on that count.

**Comment by andrewholgate** [comment]
I will look into this further but here are the results of `self-update` on both Composer and Humbug on the same server.

```
composer self-update
Updating to version 3cff4a3bb977c2ba9a09204690da128c7dceb092.
    Downloading: 100%
Use composer self-update --rollback to return to version 833ce984264204e7d6576ab082660105c7d8f04c
```

```
./humbug.phar self-update
Current version check has failed. Please try again.
```

**Comment by padraic** [comment]
@andrewholgate New phar build doesn't hide errors, and has split exceptions into two possible issues. Let me know if that creates some useful output for you.

**Comment by padraic** [comment]
Closing pending feedback. Please feel free to reopen if this issue is still a problem.
