### ISSUE TITLE
[feature request] Improve log

### ISSUE THREAD

**Issue by aledeg** [padraic/humbug#114]
I think it would be nice to have more information in the log file. Here is the list of the improvements I would love to see:
 * Result count in the title: instead of `Escapes`, having `Escapes (120)` for instance
 * Section with mutants not covered by tests similar to `Escapes` or `Errors` sections

**Comment by padraic** [comment]
Closing on the following basis: The main change noted is to list mutants not covered by tests, however that can be resolved (mostly) through Line Code Coverage analysis. It's not a Mutation Testing target and indeed we literally skip over such mutants as a performance optimisation. Logging them does no good until tests covering them actually exist.
