### ISSUE TITLE
Missing \Humbug\Command\Configure class

### ISSUE THREAD

**Issue by aztech-dev** [padraic/humbug#118]
Current master branch is broken as the console application tries to load \Humbug\Command\Configure which is not included in the project.

Ref https://github.com/padraic/humbug/pull/117/files#diff-b7620e4d0183e0945db8e010aafee3c7R23

**Comment by rollenes** [comment]
As I was working on some other feature I left it there accidently.

**Comment by aztech-dev** [comment]
Thanks for the fix :)
