### ISSUE TITLE
Incorrect mutation generated for by ref assignments

### ISSUE THREAD

**Issue by aztech-dev** [padraic/humbug#119]
When testing against code such as 

```
$var = & $otherVariable
```

a `\Humbug\Mutator\Arithmetic\BitwiseAnd` mutation is generated for the line, which always errors as it results in invalid syntax.

**Comment by padraic** [comment]
Presumably, the mutator assumes `=&` instead of `= &`.

**Comment by padraic** [comment]
@aztech-dev Should I be closing this after the PR?

**Comment by aztech-dev** [comment]
Yup all good now :) sorry forgot to do it before
