### ISSUE TITLE
Humbug has problems with multiple testsuites

### ISSUE THREAD

**Issue by jg-development** [padraic/humbug#129]
I think humbug has some problems, if the phpunit.xml is configured with multiple testsuites.
I have a phpunit.xml like this:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<phpunit bootstrap="./Bootstrap.php">
    <testsuites>
        <testsuite name="module">
            <directory>../../../module/foo/tests/unit</directory>
            <directory>../../../module/bar/tests/unit</directory>
        </testsuite>
    </testsuites>
    <php>
        <ini name="memory_limit" value="1G"/>
        <ini name="error_reporting" value="30719"/>
        <env name="APPLICATION_ENV" value="development"/>
    </php>
    <filter>
        <whitelist>
            <directory suffix=".php">../../../module/foo/src</directory>
            <directory suffix=".php">../../../module/bar/src</directory>
        </whitelist>
    </filter>
</phpunit>
```
The result ist:
```bash
Humbug version 1.0-dev

Humbug running test suite to generate logs and code coverage data...

   25 [==========================================================] 7 secs

Humbug has completed the initial test run successfully.
Tests: 25 Line Coverage: 71.48%

Humbug is analysing source files...

Mutation Testing is commencing on 22 files...
(.: killed, M: escaped, S: uncovered, E: fatal error, T: timed out)

.SSSSSS.....SS

14 mutations were generated:
       6 mutants were killed
       8 mutants were not covered by tests
       0 covered mutants were not detected
       0 fatal errors were encountered
       0 time outs were encountered

Out of 6 test covered mutations, 100% were detected.
Out of 14 total mutations, 43% were detected.
Out of 14 total mutations, 43% were covered by tests.

```

With multiple Testsuites:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<phpunit bootstrap="./Bootstrap.php">
    <testsuites>
        <testsuite name="foo">
            <directory>../../../module/foo/tests/unit</directory>
        </testsuite>
        <testsuite name="bar">
            <directory>../../../module/bar/tests/unit</directory>
        </testsuite>
    </testsuites>
    <php>
        <ini name="memory_limit" value="1G"/>
        <ini name="error_reporting" value="30719"/>
        <env name="APPLICATION_ENV" value="development"/>
    </php>
    <filter>
        <whitelist>
            <directory suffix=".php">../../../module/foo/src</directory>
            <directory suffix=".php">../../../module/bar/src</directory>
        </whitelist>
    </filter>
</phpunit>
```
The result ist:
```bash
Humbug version 1.0-dev

Humbug running test suite to generate logs and code coverage data...

   25 [==========================================================] 7 secs

Humbug has completed the initial test run successfully.
Tests: 25 Line Coverage: 71.48%

Humbug is analysing source files...

Mutation Testing is commencing on 22 files...
(.: killed, M: escaped, S: uncovered, E: fatal error, T: timed out)

MSSSSSSMMMMMSS

14 mutations were generated:
       0 mutants were killed
       8 mutants were not covered by tests
       6 covered mutants were not detected
       0 fatal errors were encountered
       0 time outs were encountered

Out of 6 test covered mutations, 0% were detected.
Out of 14 total mutations, 0% were detected.
Out of 14 total mutations, 43% were covered by tests.
```

All mutates are now marked as escaped. Are multiple Testsuites supported for now?

Greetings Jan

**Comment by padraic** [comment]
@jg-development It's a known issue. The development version to date has been working on the assumption of there being only one test suite while other features and the overall internal design evolved. We're at the end of that process. I think @rollenes has the final key piece which is switching from an internal PHPUnit to using the user's own installed copy, so I'll be focusing on the >1 test suite support as time permits.

**Comment by padraic** [comment]
Just making a note here on the cause of the issue. PHPUnit defines a suite as a collection of either a) tests or b) suites. So it creates a hierarchy branching out into sub-suites and eventually tests. When you create a configuration with >1 testsuite element, it creates a new level to that hierarchy which doesn't normally exist. This is what is throwing off Humbug, or more specifically the phpunit-extensions dependency.

The likely fix is to generate a simple true/false flag on whether a new hierarchy will be generated after analysing the phpunit.xml file, pass that as an argument to the phpunit-extension Listeners, and then we'll get accurate timings of the correct suite level, and be able to correctly filter for names at the correct level also.

**Comment by jg-development** [comment]
Hi,
maybe I have some time to look further into this next week. Can u give me now just a quick hint, in which file/lib I have to look? Makes it a little quicker.

Greetings Jan

**Comment by padraic** [comment]
@jg-development Made the changes already ;). Update to the current master and `composer update` to get an updated phpunit-extensions. Let me know if this solves your issues.

**Comment by jg-development** [comment]
OK thanks, I will give some feedback next week.

**Comment by jg-development** [comment]
It seems to work now. Testet with multiple Testsuites and multiple directories.
I think files will work too. --> Closed
