### ISSUE TITLE
Missing dependency? 

### ISSUE THREAD

**Issue by carnage** [padraic/humbug#133]
PHP Fatal error:  Class 'Symfony\Component\EventDispatcher\EventDispatcher' not found in 
/home/.../vendor/humbug/humbug/bin/humbug on line 24
PHP Stack trace:
PHP   1. {main}() /home/.../vendor/humbug/humbug/bin/humbug:0

Fatal error: Class 'Symfony\Component\EventDispatcher\EventDispatcher' not found in 
/home/.../vendor/humbug/humbug/bin/humbug on line 24

Call Stack:
    0.0004     246496   1. {main}() /home/.../vendor/humbug/humbug/bin/humbug:0

**Comment by padraic** [comment]
You are of course correct, since it's a direct dependency and not listed in the composer.json. I believe it was pulled automatically by another component, but that's not always reliable since dependencies can change that internally at will.
