### ISSUE TITLE
Missing bootstrap.php

### ISSUE THREAD

**Issue by moffe42** [padraic/humbug#137]
When follwing the guide on the fontpage, I get the following result

jach@jach:~/Code/CBX/api (master *%=)$ ./humbug.phar

```
 _  _            _
| || |_  _ _ __ | |__ _  _ __ _
| __ | || | '  \| '_ \ || / _` |
|_||_|\_,_|_|_|_|_.__/\_,_\__, |
                          |___/
Humbug version 1.0-dev

Humbug running test suite to generate logs and code coverage data...

    0 [>---------------------------------------------------------]  1 sec


  [Humbug\Exception\InvalidArgumentException]
  Could not find file lib/bootstrap.php working from /Users/jach/Code/CBX/api



run [-a|--adapter="..."] [-o|--options="..."] [-f|--file="..."] [-c|--constraints="..."] [-t|--timeout="..."] [-b|--no-progress-bar] [-i|--incremental]
```

What is the bootstrap.php file it is looking for? All my source code is in lib/

**Comment by padraic** [comment]
The bootstrap is likely for PHPUnit. Is there one defined in your phpunit.xml?

Also, could you run that with the `-vvv` option so that we can get the Exception backtrace?

**Comment by moffe42** [comment]
Checked out latest version this morning and it seems to be working flawlessly.
Sorry for the inconvenience, great tool!!
