### ISSUE TITLE
Create Logging Directories

### ISSUE THREAD

**Issue by zanderbaldwin** [padraic/humbug#138]
Presently, Humbug throws a `Humbug\Exception\JsonConfigException` when the logging directory specified does not exist with the message *"Directory for json logging does not exist"* using the following example `humbug.json.dist` configuration file:

```json
{
    "logs": {
        "json": "build/humbuglog.json"
    }
}
```

If I have added the `build` directory to my `.gitignore` file, all repository clones will fail the mutation testing. Although most people will see this error and add the directory, it is not ideal to have to create that directory every time in your continuous integration service (such as [Travis CI](http:://travis-ci.org)), not is it ideal to commit either the results or the empty directory designed to store those results.

**Comment by padraic** [comment]
Related PR has been merged.
