### ISSUE TITLE
Doesn't Work For Me At All

### ISSUE THREAD

**Issue by GrahamCampbell** [padraic/humbug#147]
Just tried to run this on windows, and I get this...

```

 _  _            _
| || |_  _ _ __ | |__ _  _ __ _
| __ | || | '  \| '_ \ || / _` |
|_||_|\_,_|_|_|_|_.__/\_,_\__, |
                          |___/ 
Humbug version 1.0-dev

Humbug running test suite to generate logs and code coverage data...

    0 [>---------------------------------------------------------]  1 sec

Tests must be in a fully passing state before Humbug is run.
Incomplete, skipped or risky tests are allowed.
The testing framework reported an exit code of 1.

```

**Comment by GrahamCampbell** [comment]
NB, this is using the latest phar. It seems work ok if I install it with composer.

**Comment by padraic** [comment]
A new phar build is pending based on the current master. It solves a few edge cases, so it sounds like it will solve this one too. I'll be rolling it out later today.

**Comment by GrahamCampbell** [comment]
Great. :)

**Comment by padraic** [comment]
This will also be Alpha 1, I think. I can count the remaining issues using one hand and zero feet.

**Comment by padraic** [comment]
@GrahamCampbell Let me know if the new phar works, and hopefully I can close this. Fingers crossed ;).

**Comment by tot-ra** [comment]
Had similar problem, had to clean-up random STD output that gifsicle/ffmpeg or tests generated, because that seemed to stop humbug from execution
