### ISSUE TITLE
100% test coverage, but 12 mutants not covered?

### ISSUE THREAD

**Issue by shabbyrobe** [padraic/humbug#151]
I've got a really [tiny library](http://github.com/shabbyrobe/nope) I thought I'd chuck humbug at just to see if there's something I may have missed. The result I get is a bit strange: for a library with 100% test coverage, I get a bunch of mutants not covered by tests (with both master and 1.0.0-alpha1). I can't for the life of me work out why! Am I doing something totally wrong here?

```
Humbug has completed the initial test run successfully.
Tests: 33 Line Coverage: 100.00%

Humbug is analysing source files...

Mutation Testing is commencing on 2 files...
(.: killed, M: escaped, S: uncovered, E: fatal error, T: timed out)

ESSSSS....S..SSSSSS

19 mutations were generated:
       6 mutants were killed
      12 mutants were not covered by tests
       0 covered mutants were not detected
       1 fatal errors were encountered
       0 time outs were encountered
```

**Comment by stof** [comment]
The suggestion in https://github.com/padraic/humbug/issues/130 to add logging of locations of uncovered mutations would help to debug this.

**Comment by lulco** [comment]
@stof @shabbyrobe I just create PR #164 for this issue, please check if it helps to you

**Comment by padraic** [comment]
Closing on basis of #164 which I've merged.

**Comment by GM-Alex** [comment]
I have the same issue, I changed the line mentioned in the report like humbug would do it and run phpunit which failed. So for my understanding the code is covered 100% and tested in the way that humbug should mark it as killed. For me it seems like a bug...
