### ISSUE TITLE
The process has been signaled with signal "11".

### ISSUE THREAD

**Issue by steadweb** [padraic/humbug#160]
Hi, 

I'm running PHPUnit `4.8.21` and my config file is below:

```
{
    "source": {
        "directories": [
            "src"
        ],
        "excludes": [
            "tests"
        ]
    },
    "chdir": "tests",
    "logs": {
        "text": "humbuglog.txt"
    }
}
```

No matter what options I try, the same error is thrown. SO suggests it's a permissions issue but I have no idea what permissions humbug requires.

**Comment by MarkRedeman** [comment]
Since you were using PHPUnit `4.8.21` could you try again and check if the error is still present on the latest Humbug version? PR #162 fixed a bug due to PHPUnit so it might be that your bug has been solved.
If it hasn't been solved, can you provide some additional info?

**Comment by steadweb** [comment]
Thanks @MarkRedeman - it seems the latest version of humbug (master) has fixed this issue.
