### ISSUE TITLE
Using Humbug within CI process

### ISSUE THREAD

**Issue by krzysztof-gzocha** [padraic/humbug#188]
Hi.

I'd like to get your opinion about using Humbug as a step in continuous integration process.
I was thinking about not only running PHPUnit and mark my pull-request as failed if at least 1 test have failed, but I would also run Humbug and if there would be at least X escaped mutations (or other errors), then mark the PR as failed.

First question is: does it make sense? Would you guys like to see something like this?
Second question (if it does make sense) how do you think would be the best way to implement it?

Thanks.

**Comment by aztech-dev** [comment]
I would not recommend you do that for the following reasons:

- Mutation testing requires human review, it's very difficult to set arbitrary limits on what is and what is not an acceptable escaped mutation.
- Mutation testing is slow, and slow is the enemy of CI (waiting too long for tests to pass is annoying at best)

**Comment by krzysztof-gzocha** [comment]
Thank you, that's actually good point.
