### ISSUE TITLE
Incorrect replacement of & by |

### ISSUE THREAD

**Issue by Anahkiasen** [padraic/humbug#19]
It seems the bitwise mutator is replacing reference operators by mistake:

```php
-  foreach ($shared as &$file) {
+  foreach ($shared as |$file) {
```

Which causes a syntax error for that mutation.

**Comment by padraic** [comment]
Noted, I'll need to filter out references from replacement... Indeed, there should be anti-reference mutator all to itself.

**Comment by padraic** [comment]
This should fix nearly all uses of ampersand in referencing https://github.com/padraic/humbug/commit/fef019f7c08f565313cb9c24e72b6114f473d6a0
