### ISSUE TITLE
Should file_get_contents be tested?

### ISSUE THREAD

**Issue by mallardduck** [padraic/humbug#196]
As per the title, should `file_get_contents` really be being tested? Or is this a bug?

```
1) \Humbug\Mutator\Boolean\FalseValue
Diff on \LiquidWeb\SslCertificate\Downloader::downloadRevocationListFromUrl() in /home/dan/Projects/ssl-certificate/src/Downloader.php:
--- Original
+++ New
@@ @@
         $csrConfig = StreamConfig::configCrl();
-        $file = file_get_contents($parsedUrl->getValidatedURL(), false, $csrConfig->getContext());
+        $file = file_get_contents($parsedUrl->getValidatedURL(), true, $csrConfig->getContext());
         unset($csrConfig, $parsedUrl);
         $x509 = new X509();
         $crl = $x509->loadCRL($file); // see ev2009a.crl
         unset($x509, $file);
         return $crl;
     }
```
for further info, on this instance `$csrConfig->getContext()` is creating:
```
stream_context_create([
            'http' => [
                'method' => "GET",
                'max_redirects' => '0',
                'ignore_errors' => '1'
            ],
        ])
```

So I'm fairly confident that changing the include option (on/off) won't make a difference in my usage ever. I'm wondering if there are any instances where this should be tested? If there are none, or they are very minimal, I'm wondering if this could be ignored in testing?

Being completely literal, there's no assumption being made here; therefor no assumption to test against, right?

**Comment by padraic** [comment]
Humbug isn't intelligent enough to understand the context or impact of every mutation it makes, so you're making a valid case that this is a "false positive" outcome.

**Comment by mallardduck** [comment]
Thanks, I was figuring that's just the case and wanted to get your insight.

Is it possible to somehow ignore this case? Maybe exclude the `file_get_contents` method from being mutated somehow?

**Comment by theofidry** [comment]
You code could very well rely on the second argument of `file_get_contents` being set to `false`, so we can't ignore it unconditionally.

**Comment by mallardduck** [comment]
@theofidry understood.

I should have been more clear with my question about an exclude; I was more thinking about a project/config exclude rather than excluding it completely from humbugs testing.

As I see the project is under going some reorganization I can be patient on this issue and any related workarounds. Maybe we can work to add an exclude system in future releases. For now I'll just set this to closed and I'll keep an eye on how the project progresses!
