### ISSUE TITLE
Immediate Fatal Error on PHP 5.4

### ISSUE THREAD

**Issue by aik099** [padraic/humbug#20]
I'm getting this error immediately after I run Humbug:
```
Humbug running test suite to generate logs and code coverage data...

<warning>Tests must be in a fully passing state before Humbug is run.</warning>
<warning>Incomplete, skipped or risky tests are allowed.</warning>
<warning>Stderr: \n    > PHP Parse error:  syntax error, unexpected '"/mnt/hd/home/alex/web/g/mine/' (T_CONSTANT_ENCAPSED_STRING) in - on line 5
    > \n</warning>
```
This happens because the generated PHPUnit invocation snippet is passing a string to `empty` function, which is only allowed since PHP 5.5:

```php
if (!empty(".../vendor/autoload.php")) require_once ".../vendor/autoload.php";
```

**Comment by padraic** [comment]
I'm not wasting time on relying on 5.5 behaviour am I? :P I'll move it to a variable declaration then check. Thanks for the report!

**Comment by aik099** [comment]
> I'm not wasting time on relying on 5.5 behaviour am I?

Nope. But as long as `composer.json` says that library is PHP 5.4 compatible, then it should be. I wonder why Travis tests haven't detected that.

I don't see any commits that fixed the issue. Why have you closed. I have PR on the way by the way.

**Comment by aik099** [comment]
The 44507175fee6b8e4cb61634faa8016d4d80a9a97 commit contained a fix.

**Comment by padraic** [comment]
Apologies, I should have reference a fix.

**Comment by aik099** [comment]
I usually add "Closes #xxx" where "xxx" is task number in the commit message and then GitHub both will associated this commit and close the issue automatically.
