### ISSUE TITLE
Check code coverage whitelisting variations

### ISSUE THREAD

**Issue by padraic** [padraic/humbug#28]
Reminder to self on a passing Tweet about failing code coverage generation. Humbug only tells PHPUnit to do it, but our XML config rewrites may be omitting essential info in certain cases.

**Comment by DennisBecker** [comment]
I have a phpunit.xml created with the following content:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<phpunit strict="true"
		 backupGlobals="false"
		 backupStaticAttributes="false"
		 colors="true"
		 convertErrorsToExceptions="true"
		 convertNoticesToExceptions="true"
		 convertWarningsToExceptions="true"
		 processIsolation="false"
		 stopOnFailure="false"
		 syntaxCheck="false"
		 bootstrap="tests/bootstrap.php"
		>
	<php>
		<ini name="intl.error_level" value="-1"/>
		<ini name="memory_limit" value="-1"/>
	</php>

	<testsuite name="Test Suite">
		<directory>./tests</directory>
	</testsuite>

	<filter>
		<whitelist processUncoveredFilesFromWhitelist="true">
			<directory suffix=".php">./src</directory>
		</whitelist>
	</filter>

	<logging>
		<log type="coverage-html" target="build/coverage" title="Test Suite"
			 charset="UTF-8" yui="true" highlight="true"
			 lowUpperBound="35" highLowerBound="70"/>
		<log type="coverage-clover" target="build/logs/clover.xml"/>
		<log type="junit" target="build/logs/junit.xml"
			 logIncompleteSkipped="false"/>
	</logging>
</phpunit>
```

Humbug still doesn't work after running the PHPUnit tests it fails with exception Humbug\Exception\InvalidArgumentException "File does not exist:" 
```
Exception trace:
 () at /Users/becker/.composer/vendor/humbug/humbug/src/Humbug/Utility/CoverageData.php:34
 Humbug\Utility\CoverageData->__construct() at /Users/becker/.composer/vendor/humbug/humbug/src/Humbug/Adapter/Phpunit.php:178
 Humbug\Adapter\Phpunit->getCoverageData() at /Users/becker/.composer/vendor/humbug/humbug/src/Humbug/Command/Humbug.php:145
 Humbug\Command\Humbug->execute() at /Users/becker/.composer/vendor/symfony/console/Symfony/Component/Console/Command/Command.php:253
 Symfony\Component\Console\Command\Command->run() at /Users/becker/.composer/vendor/symfony/console/Symfony/Component/Console/Application.php:874
 Symfony\Component\Console\Application->doRunCommand() at /Users/becker/.composer/vendor/symfony/console/Symfony/Component/Console/Application.php:195
 Symfony\Component\Console\Application->doRun() at /Users/becker/.composer/vendor/symfony/console/Symfony/Component/Console/Application.php:126
 Symfony\Component\Console\Application->run() at /Users/becker/.composer/vendor/humbug/humbug/bin/humbug:23
```

Do you need more information?

**Comment by padraic** [comment]
I'll be investigating. I'm not sure about logging priority between the command line and the XML conf. Humbug sets a command line option to generate PHP coverage (we can't use XML/HTML since they don't map specific tests to lines). Most likely solution is add that to the XML conf rewrite (the one Humbug generates is based on the original - we don't use the original directly) so you'd have a line (assuming default cache dir of /tmp):

```
<log type="coverage-php" target="/tmp/coverage.humbug.php"/>
```
If you add that to <logging>, I would expect Humbug to trundle away happily.

**Comment by DennisBecker** [comment]
I have changed the phpunit.xml file to only log coverage-php as you pointed out, but I still get the same error.

I'm using PHPUnit 4.4.1.

**Comment by padraic** [comment]
```php
$container->getCacheDirectory() . '/coverage.humbug.php'
```
Assuming cache is the default (it is - it's not configurable for now), sys_get_temp_dir(), then this should never be causing that exception if the code coverage is being generated and exists in /tmp

In any case, will be testing more. If you happen to have this example in the open, a link or reproducible case would be a huge assist. At present, we're most of the way towards breaking a direct link to the existing phpunit, but we do still need a Humbug copy - it's the only good way to configure phpunit.

**Comment by padraic** [comment]
@DennisBecker Not sure if it helps, need a reproducible case, however coverage logging is now handled solely with the XML conf and we remove all original references. Humbug should now undoubtedly be running coverage when needed - only other factor I can think of preventing it is a PHPUnit issue.

**Comment by DennisBecker** [comment]
I'm just an idiot!

Which extension do you need for code coverage? So yeah, xdebug was installed but not loaded.

Prime time - now it works. Sorry for that and thanks for your effort!

**Comment by padraic** [comment]
:P No worries!
