### ISSUE TITLE
mybuilder/phpunit-accelerator dev-shutdownfunction not exists

### ISSUE THREAD

**Issue by urmaul** [padraic/humbug#29]
Just got this problem from composer:

  Problem 1
    - Installation request for humbug/humbug 1.0.*@dev -> satisfiable by humbug/humbug[1.0.x-dev].
    - humbug/humbug 1.0.x-dev requires mybuilder/phpunit-accelerator dev-shutdownfunction -> no matching package found.

**Comment by padraic** [comment]
Yeah, Composer is being naughty and ignoring the custom branch. C'est la vie. It's not an absolutely critical dependency but it needs some patching. I'll remove it for the moment.
