### ISSUE TITLE
Mutation idea: removing "return $this;" statements

### ISSUE THREAD

**Issue by roman-tsiupa-sociomantic** [padraic/humbug#3]
I often use methods that return $this so they are chainable. And more than a few time I saw that here and there I forget to check for that in my tests. I guess a lot of people may do the same. 

At first I was thinking to suggest a mutation that would remove all return statements, but that seems a bit too much, which "return $this" is a very popular use case

**Comment by padraic** [comment]
It's a good idea, and actually a very well intended one. What I'd expect to be adding against return values would be:

* Turn true to false, and vice versa
* Invert integers (* -1), or increment zeroes
* Unknown variables, return null
* Replace blank/null return statements with exception throws

That should be enough to throw a few spanners around the works ;). Probably a few other things we could try.

**Comment by padraic** [comment]
I've added this: https://github.com/padraic/humbug/blob/master/src/Humbug/Mutator/ReturnValue/This.php

**Comment by padraic** [comment]
Closing as implemented. Will expand on this shortly for literal value returns and from there, we shall see.

**Comment by roman-tsiupa-sociomantic** [comment]
Cool thanks!

**Comment by padraic** [comment]
@roman-tsiupa-sociomantic No problem ;). The hard task is going to be figuring out whether I can check return values of random vars for mutation. That...should be interesting.
