### ISSUE TITLE
Humbug unexpectedly ends up with "Tests must be in a fully passing state..."

### ISSUE THREAD

**Issue by ksimka** [padraic/humbug#31]
Sometimes humbug does this

    Humbug running test suite to generate logs and code coverage data...
    
      118 [==========================================================] 11 secs

    <warning>Tests must be in a fully passing state before Humbug is run.</warning>
    <warning>Incomplete, skipped or risky tests are allowed.</warning>
    <warning>Stdout: \n    > 1..120
        >
        > Generating code coverage report in PHP format ... done
        > \n</warning>

(Yes, tags are printed, not converted)
Tests are really ok, and the strange thing is that after manually running phpunit (and ensure that tests are really ok) this error disappears, otherwise you will get this error every time. Looks like some cache issue.

**Comment by padraic** [comment]
It looks like an issue processing the TAP output. The stdout is actually truncated at the moment (had issues on bigger libraries with many thousands of tests creating a memory sink). Will look into it.

**Comment by padraic** [comment]
I add more of a safety net. The TAP parsing appears correct, but I may be racing against the initial process closing (if open just long enough, the exit code would be null, not 0 or 1 as expected). Explicitly closing it should do the trick so will consider this one fixed!
