### ISSUE TITLE
How to debug humbug?

### ISSUE THREAD

**Issue by ksimka** [padraic/humbug#32]
Still can't get humbug work for me. Ends up with

```
Humbug is analysing source files...

Mutation Testing is commencing...
(.: killed, M: escaped, S: uncovered, E: fatal error, T: timed out)

SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS |   60 (14/72)
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS |  120 (42/72)
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS |  180 (52/72)
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS |  240 (55/72)
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS |  300 (63/72)
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS |  360 (69/72)
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS |  420 (69/72)
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS


  [Symfony\Component\Finder\Exception\AccessDeniedException]
  RecursiveDirectoryIterator::__construct(/tmp/phpcs-pre-receive-hook.UjazU6RA): failed to open dir: Permission denied






  [UnexpectedValueException]
  RecursiveDirectoryIterator::__construct(/tmp/phpcs-pre-receive-hook.UjazU6RA): failed to open dir: Permission denied
```

I want to know why humbug needs that file, but debugging it is kinda hard :)  Is there any debug mode or something that helps to get at least the line number of the error, not only exception type and a message? Or please show me that place in code where exceptions are catched, so I can get more information about this issue.

**Comment by padraic** [comment]
@ksimka Exception traces are available by passing -vvv on cli (it's a symfony console app). Above is a Symfony Finder exception. I've added a fix to ignore unreadables. Let me know if that resolves.

**Comment by ksimka** [comment]
You've made a mistype, double `->`.

**Comment by ksimka** [comment]
I've fixed locally and yes, this resolves the issue, thanks! You can close after fixing typo.

**Comment by padraic** [comment]
Darn typo! Fixed now.
