### ISSUE TITLE
Replace junit logging with custom listener and test level priority queuing

### ISSUE THREAD

**Issue by padraic** [padraic/humbug#35]
The junit stuff is just bugging me right now. It's hacky, finnicky an all other sorts of icky.

**Comment by pfrenssen** [comment]
I also have problems with jUnit when trying to run humbug on the Drupal code base. For some reason the `/tmp/junitlog.humbug.xml` file is empty after the analysis step. This later results in this exception:

> Humbug\Exception\InvalidArgumentException: Drupal\Tests\node\Unit\Plugin\views\field\NodeBulkFormTest does not exist on previously generated JUnit log

**Comment by padraic** [comment]
@pfrenssen I have a cleaner JSON format up and running for the future phpspec integration over at https://github.com/padraic/phpspec-extensions. I'll just port that into a PHPUnit listener and we'll be flying :).

After I write more unit tests...;)

**Comment by padraic** [comment]
Closing as implemented in current master.
