### ISSUE TITLE
The requested PHP extension ext-xdebug ^2.1.4 is missing from your system.

### ISSUE THREAD

**Issue by pfrenssen** [padraic/humbug#42]
When running `composer install` on my Arch Linux system with PHP 5.6.4 and xdebug 2.2.6 I get the following error message:

> The requested PHP extension ext-xdebug ^2.1.4 is missing from your system.

This is probably a bug in composer rather than in humbug.

**Comment by GrahamCampbell** [comment]
Try running `composer self-update` and `composer clear-cache`.

**Comment by padraic** [comment]
What vesion of xdebug is actually reported? There might be a version naming issue.

**Comment by GrahamCampbell** [comment]
I suspect it's just an out of date version of composer, so it's looking for a version actually called "^2.1.4".

**Comment by pfrenssen** [comment]
@GrahamCampbell is correct, after I updated composer I no longer had the error. Thanks a lot!

**Comment by GrahamCampbell** [comment]
Please close this.
