### ISSUE TITLE
FunctionCall Mutator falsely triggered

### ISSUE THREAD

**Issue by jg-development** [padraic/humbug#51]
The FunctionCall Mutator reacts to statements like: "return true;".
I added a UnitTests with a pull request with this Problem.

Another UnitTest from yourself is hinting to the problem, too.
Humbug\Test\MutableTest::testShouldGenerateBooleanFalseMutationWhenBoolFalseDetected

Greetings
Jan

padraic/humbug#55

**Comment by padraic** [comment]
Fixed in master. Thanks for reporting!
