### ISSUE TITLE
Humbug doesn't properly kill mutations that run into timeout

### ISSUE THREAD

**Issue by SvenRtbg** [padraic/humbug#63]
My humbug run reports nine timeouts - and after finishing the run, I have nine processes "php5" on my machine running forever and eating significant amounts of CPU.

I'd expect humbug to kill these endless loops. :)

I currently use commit a3e6269 for this.

**Comment by SvenRtbg** [comment]
It seems like there is some messy situation with Symfony\Process not correctly detecting the real process ID and/or not correctly killing child processes. Please see http://symfony.com/doc/current/components/process.html#process-signals for some pointers to issue tickets explaining the situation.

**Comment by padraic** [comment]
Reopening the issue, primarily because the fix is currently scoped only to non-Windows environments. Will need feedback on whether the fix is Windows compatible, or if the problem persists there also before closing it off.
