### ISSUE TITLE
Run Humbug/PHPUnit for single Classes/Files

### ISSUE THREAD

**Issue by jg-development** [padraic/humbug#82]
A humbug run for single Tests would achieve faster results and results in faster analysis of the errors.
I hope this feature might come?

**Comment by padraic** [comment]
It's on the cards! The phpunit-extensions package I wrote will allow for finer grained control over the classes and tests we can target. It does all need to wired into the command options. I'll leave the issue open here as an enhancement.

**Comment by bcdennis** [comment]
+1

**Comment by padraic** [comment]
Implemented in master. Humbug does not analyse for classes per se, but there's a new command line option where you can up an array of names/globs/regexes that are passed to the Symfony Finder instance used to locate files to mutate.
