### ISSUE TITLE
Cannot install humbug via composer

### ISSUE THREAD

**Issue by young-steveo** [padraic/humbug#85]
When attempting to install humbug via composer, I get the following error message:

> Your requirements could not be resolved to an installable set of packages.
>  [...]
>   humbug/humbug dev-master requires padraic/phpunit-extensions ~1.0@dev -> no matching package found.

**Comment by Anahkiasen** [comment]
You need to add `"minimum-stability": "dev"` to your composer file, Humbug is not tagged yet

**Comment by young-steveo** [comment]
:+1:
