### ISSUE TITLE
[rfc] use psr-4 under src/ directly

### ISSUE THREAD

**Issue by samsonasik** [padraic/humbug#89]
currently, directory structure is ( "like" psr-0 but set psr-4 in src/Humbug )  : 
```
src
   Humbug/
         Adapter
         Utility
  bootstrap.php
```
How about use psr-4 under src/ directly so directory structure will be like this : 
```
src
     Adapter
     Utility
bootstrap.php
```
?

**Comment by padraic** [comment]
I have no objections :+1:

**Comment by samsonasik** [comment]
I created pr #91 for it.  how about tests/ directory too ?

**Comment by padraic** [comment]
I would do same for tests also for consistency.

**Comment by samsonasik** [comment]
@padraic done ;). I've updated #91 for tests/ folder too ;)
